import os
import re

from PIL import Image

# Scans every barrel file in src/images/ for '@resources/...' imports, reads
# each raster image's real dimensions off disk, and writes a generated module
# that registers each one's aspect ratio (see imageDimensions.ts). PortfolioImage
# uses this to reserve the exact loading-placeholder space per image instead of
# guessing, eliminating loading-time layout shift.
#
# Re-run this (from the repo root) after adding, removing, or replacing any
# image referenced from src/images/*.ts. Unlike generateImageImport.py, this
# writes directly to its final location — no manual move required.

BARREL_DIR = 'src/images'
OUTPUT_PATH = 'src/images/generatedImageDimensions.ts'
SKIP_FILES = {'index.ts', 'generatedImageDimensions.ts', 'imageDimensions.ts'}
RASTER_EXTENSIONS = {'jpg', 'jpeg', 'png'}


def find_imported_image_paths():
    paths = []
    seen = set()
    for fname in sorted(os.listdir(BARREL_DIR)):
        if not fname.endswith('.ts') or fname in SKIP_FILES:
            continue
        with open(os.path.join(BARREL_DIR, fname)) as f:
            content = f.read()
        for match in re.finditer(r"from '@resources/([^']+)'", content):
            path = match.group(1)
            if path.split('.')[-1].lower() in RASTER_EXTENSIONS and path not in seen:
                seen.add(path)
                paths.append(path)
    return paths


def main():
    paths = find_imported_image_paths()

    import_lines = []
    register_lines = []
    for index, path in enumerate(paths):
        full_path = os.path.join('resources', path)
        with Image.open(full_path) as image:
            width, height = image.size
        var_name = f'img{index}'
        import_lines.append(f"import {var_name} from '@resources/{path}';")
        register_lines.append(f'registerImageAspectRatio({var_name}, {width}, {height});')

    header = (
        '// AUTO-GENERATED by generateImageDimensions.py — do not hand-edit.\n'
        '// Re-run `python3 generateImageDimensions.py` from the repo root after\n'
        '// adding, removing, or replacing any image referenced from src/images/*.ts.\n'
        '//\n'
        '// Populates the aspect-ratio registry (see imageDimensions.ts) so\n'
        '// PortfolioImage can reserve the exact space for each image instead of\n'
        '// guessing, eliminating loading-time layout shift.\n'
        "import { registerImageAspectRatio } from './imageDimensions';\n\n"
    )
    body = '\n'.join(import_lines) + '\n\n' + '\n'.join(register_lines) + '\n'

    with open(OUTPUT_PATH, 'w') as f:
        f.write(header + body)

    print(f'Wrote {OUTPUT_PATH} with {len(paths)} images')


if __name__ == '__main__':
    main()
